name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Skip duplicate runs
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'true'
          skip_after_successful_duplicate: 'true'
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test